fix(chat): Connected font sizes to Theme properties
status-im/status-app pull request #7723
Opened 2022-10-03 14:05 UTC by igor-sirotin

Fixes https://github.com/status-im/status-desktop/issues/7708

### What does the PR do

* Copied font size properties from old `Style` to StatusQ's `Theme`
   I will replace the old function with the new one in a separate PR, if this one's alright
* Attached chat fonts to the new `Theme` properties
* Added text/value roles to `StatusLabeledSlider`

### Affected areas

chat, theme

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

https://user-images.githubusercontent.com/25482501/193597551-2579a8dc-34e0-4b07-8b00-ab4a80237b2a.mov

2022-10-03 14:08 UTC, caybro approved these changes
LGTM

2022-10-03 14:11 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 15015236 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7723/1/) | 2022-10-03 14:11:45 | ~5 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7723/1//consoleText) |

2022-10-03 16:44 UTC, MishkaRogachev approved these changes
Cool!

2022-10-04 10:02 UTC, anastasiyaig commented
@MishkaRogachev I cant start the build from this PR:

```INF 2022-10-04 13:01:51.594+03:00 starting application...                    topics="status-app" tid=5405045 file=nim_status_client.nim:175
Error while loading QML: QUrl("qrc:/main.qml")
```

2022-10-04 10:18 UTC, caybro commented
> @igor-sirotin I cant start the build from this PR:
> 
> ```
> Error while loading QML: QUrl("qrc:/main.qml")
> ```

There should be more errors prior to that

2022-10-04 10:24 UTC, anastasiyaig commented
> > @igor-sirotin I cant start the build from this PR:
> > ```
> > Error while loading QML: QUrl("qrc:/main.qml")
> > ```
> 
> There should be more errors prior to that

```
INFO [10-04|13:01:50.643] Status backend initialized               backend=geth version=0.110.2 commit=d89c0c8d IpfsGatewayURL=https://ipfs.status.im/
INF 2022-10-04 13:01:51.308+03:00 Version: 0.6.0                             topics="status-app" tid=5405045 file=nim_status_client.nim:168
INF 2022-10-04 13:01:51.308+03:00 Commit: 150152369                          topics="status-app" tid=5405045 file=nim_status_client.nim:169
INF 2022-10-04 13:01:51.309+03:00 Current date:                              topics="status-app" tid=5405045 file=nim_status_client.nim:170 currentDateTime=2022-10-04T13:01:51+03:00
INF 2022-10-04 13:01:51.309+03:00 starting application controller...         topics="status-app" tid=5405045 file=nim_status_client.nim:172
DBG 2022-10-04 13:01:51.309+03:00 init keycard using                         topics="keycard-service" tid=5405045 file=service.nim:79 pairingsJson=/Users/anastasiya/data/StatusPR1/data/keycard/pairings.json
DBG 2022-10-04 13:01:51.309+03:00 initialization response:                   topics="keycard-service" tid=5405045 file=service.nim:81 initResp=ok
QQmlApplicationEngine failed to load component
qrc:/main.qml:282:9: Type AppMain unavailable
qrc:/app/mainui/AppMain.qml:167:47: Type ProfilePopup unavailable
qrc:/imports/shared/popups/ProfilePopup.qml:389:9: Type SharedViews.ProfileView unavailable
qrc:/imports/shared/views/ProfileView.qml:368:9: Type MessageView unavailable
qrc:/imports/shared/views/chat/MessageView.qml:362:9: Type StatusMessage unavailable
qrc:/StatusQ/src/StatusQ/Components/StatusMessage.qml:281:17: Type StatusMessageHeader unavailable
qrc:/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml:73:13: Cannot assign to non-existent property "pixelSize"
INF 2022-10-04 13:01:51.594+03:00 starting application...                    topics="status-app" tid=5405045 file=nim_status_client.nim:175
Error while loading QML: QUrl("qrc:/main.qml")
```
@caybro this is the full one

2022-10-04 10:29 UTC, caybro requested changes

2022-10-04 10:29 UTC, caybro commented on ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
> +            pixelSize: Theme.asideTextFontSize
Here's the bugger :)

2022-10-04 10:31 UTC, anastasiyaig commented on ui/StatusQ/src/StatusQ/Components/private/statusMessage/StatusMessageHeader.qml
> +            pixelSize: Theme.asideTextFontSize
thank you for digging in @caybro !

2022-10-04 11:01 UTC, caybro approved these changes

2022-10-04 12:13 UTC, anastasiyaig approved these changes

2022-10-04 12:14 UTC, merged

2026-08-19 20:56 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | a435c861 | [508](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/508/) | 2026-08-19 20:56:06 | ~13 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260819-200320-a435c8-pr7723-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260819-200320-a435c8-pr7723-arm64.apk&size=400x400&errorCorrectionLevel=L)|