fix(AppMain): only show banner when disconnected
status-im/status-app pull request #7748
Opened 2022-10-04 16:40 UTC by alexandraB99

Closes #7416

### What does the PR do
Banners: only show banner when disconnected

### Affected areas
Banners

2022-10-04 16:44 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | d924ba11 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7748/1/) | 2022-10-04 16:44:49 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7748/1//consoleText) |

2022-10-04 16:54 UTC, caybro reviewed
How does it auto hide when the user is back online?

2022-10-04 16:55 UTC, caybro requested changes
I think this will break: 
- the autohiding when the user comes back online
- it will still say "Disconnected" even when online

2022-10-05 13:16 UTC, alexandraB99 commented
> I think this will break:
> 
>     * the autohiding when the user comes back online
> 
>     * it will still say "Disconnected" even when online

you're right! added back the check, if it's connected to hide.

2022-10-05 14:03 UTC, caybro approved these changes

2022-10-05 14:10 UTC, igor-sirotin reviewed
I might be wrong, but I thought we agreed that:
the banner shouldn't show "Connected" at startup, BUT it should change to green "connected" when the connection is restored.

2022-10-06 14:21 UTC, micieslak requested changes
Some questions/doubts

2022-10-06 14:21 UTC, micieslak commented on ui/app/mainui/AppMain.qml
> -                        text: isConnected ? qsTr("Connected") : qsTr("Disconnected")
If I understand correctly, "Connected" is also needed, when we go back online after being some time offline.

2022-10-06 14:21 UTC, micieslak commented on ui/app/mainui/AppMain.qml
> +                                hide();
It seems to be never shown

2022-10-07 11:25 UTC, igor-sirotin requested changes
We agreed with @alexandraB99 that there should still be "Connected" banner, we just don't want to see it at application startup 🙂

2022-10-07 17:14 UTC, alexandraB99 commented
> We agreed with @alexandraB99 that there should still be "Connected" banner, we just don't want to see it at application startup 🙂

@igor-sirotin changed it as agreed, however I am not sure this is the correct variable to set to true as I can still see it on startup but I will check this further. Marking as `do not merge` for now

2022-10-12 00:07 UTC, elina2015 commented
@alexandraB99 I still can see the banner 'Connected' on the startup. After disconnecting and connecting again, the banner doesn't appear. Could you kindly check?

2022-10-12 00:07 UTC, elina2015 requested changes
Need fixes

2022-10-18 15:35 UTC, alexandraB99 commented
@elina2015, @micieslak "After disconnecting and connecting again, the banner doesn't appear." -> this is not a result of this PR, it also happens in master. @igor-sirotin setting `isConnected` to true in nim didn't have any affect as it seems that local `isConnected` property was false until Component initialization. this solution seems working fine.

2022-10-18 22:16 UTC, elina2015 approved these changes
Tested and approved

2022-10-19 11:32 UTC, micieslak requested changes

2022-10-20 14:41 UTC, alexandraB99 commented on ui/app/mainui/AppMain.qml
> +                            connectedBannerComponent.isConnected = bannersLayout.isConnected;
good catch! I missed the reference to a Component. Code updated, please have a second look!

2022-10-20 20:11 UTC, micieslak commented on ui/app/mainui/AppMain.qml
> +                            connectedBannerComponent.isConnected = bannersLayout.isConnected;
Thank you @alexandraB99 for amending! Now it looks and works nice :+1:

2022-10-20 20:11 UTC, micieslak approved these changes

2022-10-24 12:45 UTC, igor-sirotin approved these changes
Looks good, thanks!

2022-10-25 11:24 UTC, merged

2026-08-21 20:43 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (29)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 8415c54e | [564](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/564/) | 2026-08-21 20:43:45 | ~12 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-201939-8415c5-pr7748-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260821-201939-8415c5-pr7748-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | 8415c54e | [566](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/566/) | 2026-08-21 21:09:30 | ~15 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-205249-8415c5-pr7748-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260821-205249-8415c5-pr7748-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | 8415c54e | [2089](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/2089/) | 2026-08-21 21:12:59 | ~19 min | `linux/x86_64` | [:package:`tgz`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-205249-8415c5-pr7748-x86_64.tar.gz) |
| :heavy_check_mark: | 8415c54e | [464](https://ci.status.im/job/status-app/job/systems/job/ios/job/aarch64/job/package/464/) | 2026-08-21 21:23:19 | ~29 min | `ios/aarch64` | [:iphone:`ipa`](https://i.diawi.com/2GMTLP) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fi.diawi.com%2F2GMTLP&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | 8415c54e | [2194](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2194/) | 2026-08-21 21:24:34 | ~30 min | `macos/aarch64` | [:apple:`dmg`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-205249-8415c5-pr7748-aarch64.dmg) |
| :heavy_check_mark: | 8415c54e | [1953](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/package/1953/) | 2026-08-21 21:28:42 | ~34 min | `windows/x86_64` | [:cd:`exe`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-205249-8415c5-pr7748-x86_64.exe) |
| :heavy_check_mark: | 8415c54e | [575](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/575/) | 2026-08-21 21:29:21 | ~15 min | `tests/e2e` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/575/allure/) |
| | | | | | | |
| :heavy_multiplication_x: | c78e3ac1 | [659](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/659/) | 2026-08-21 21:48:21 | ~18 min | `tests/e2e-windows` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/659/allure/) |
| | | | | | | |
| :heavy_check_mark: | a152a8bd | [572](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/572/) | 2026-08-22 22:36:12 | ~12 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260822-222300-a152a8-pr7748-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260822-222300-a152a8-pr7748-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | a152a8bd | [2097](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/2097/) | 2026-08-22 22:41:53 | ~18 min | `linux/x86_64` | [:package:`tgz`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260822-222300-a152a8-pr7748-x86_64.tar.gz) |
| :heavy_check_mark: | a152a8bd | [470](https://ci.status.im/job/status-app/job/systems/job/ios/job/aarch64/job/package/470/) | 2026-08-22 22:42:32 | ~19 min | `ios/aarch64` | [:iphone:`ipa`](https://i.diawi.com/S6LziM) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fi.diawi.com%2FS6LziM&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | a152a8bd | [2200](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2200/) | 2026-08-22 22:48:01 | ~24 min | `macos/aarch64` | [:apple:`dmg`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260822-222300-a152a8-pr7748-aarch64.dmg) |
| :heavy_check_mark: | a152a8bd | [583](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/583/) | 2026-08-22 22:57:31 | ~15 min | `tests/e2e` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/583/allure/) |
| :heavy_check_mark: | a152a8bd | [1961](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/package/1961/) | 2026-08-22 23:07:22 | ~43 min | `windows/x86_64` | [:cd:`exe`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260822-222300-a152a8-pr7748-x86_64.exe) |
| :heavy_check_mark: | a152a8bd | [667](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/667/) | 2026-08-22 23:27:40 | ~19 min | `tests/e2e-windows` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/667/allure/) |
| | | | | | | |
| :heavy_check_mark: | af61a2ca | [634](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/634/) | 2026-08-25 20:16:55 | ~16 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-200015-af61a2-pr7748-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260825-200015-af61a2-pr7748-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | af61a2ca | [2167](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/2167/) | 2026-08-25 20:35:16 | ~20 min | `linux/x86_64` | [:package:`tgz`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-200015-af61a2-pr7748-x86_64.tar.gz) |
| :heavy_check_mark: | af61a2ca | [532](https://ci.status.im/job/status-app/job/systems/job/ios/job/aarch64/job/package/532/) | 2026-08-25 20:41:36 | ~34 min | `ios/aarch64` | [:iphone:`ipa`](https://i.diawi.com/ATFqzn) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fi.diawi.com%2FATFqzn&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | af61a2ca | [639](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/639/) | 2026-08-25 20:51:07 | ~15 min | `tests/e2e` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/639/allure/) |
| :heavy_check_mark: | af61a2ca | [2266](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2266/) | 2026-08-25 20:59:39 | ~24 min | `macos/aarch64` | [:apple:`dmg`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-200015-af61a2-pr7748-aarch64.dmg) |
| :heavy_check_mark: | af61a2ca | [2023](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/package/2023/) | 2026-08-25 22:13:10 | ~45 min | `windows/x86_64` | [:cd:`exe`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-200015-af61a2-pr7748-x86_64.exe) |
| :heavy_multiplication_x: | af61a2ca | [714](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/714/) | 2026-08-25 22:30:58 | ~17 min | `tests/e2e-windows` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/714/allure/) |
| :heavy_check_mark: | af61a2ca | [641](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/641/) | 2026-08-26 10:05 [...]