fix: display "Resend" for expired messages
status-im/status-app pull request #7749
Opened 2022-10-04 18:35 UTC by richard-ramos

2022-10-04 18:36 UTC, alaibe approved these changes

2022-10-04 21:03 UTC, caybro approved these changes

2022-10-04 21:03 UTC, caybro commented on src/app/modules/shared_models/message_model.nim
> +    echo "IND IS", ind
Leftover debug?

2022-10-05 12:11 UTC, richard-ramos commented on src/app/modules/shared_models/message_model.nim
> +    echo "IND IS", ind
oops

2022-10-05 13:02 UTC, MishkaRogachev approved these changes

2022-10-20 01:22 UTC, elina2015 commented
@richard-ramos hey, it seems the build is not correct - after launching it's closing without any notification. Could you kindly rebuild?

2022-10-20 01:23 UTC, elina2015 requested changes
The build doesn't work - macOS Monterey

2022-10-21 06:16 UTC, elina2015 commented
@richard-ramos hey, I sent few messages in the test chat after disconnecting (the 'Disconnected' banner appeared) and after sending the messages I reconnected back. But the Resend option is not shown:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/14942081/197125652-1371a155-19c8-4ea0-8cb3-3f0f41a27fb6.png">
At the same time, my  offline messages are nor shown for other users (it's a proof that they weren't sent):
<img width="882" alt="image" src="https://user-images.githubusercontent.com/14942081/197125761-233b26ad-122a-41b7-8858-22df63332447.png">
Could you  kindly check it?

2022-10-25 13:42 UTC, richard-ramos commented
Looking into this issue, i saw something interesting that would require some UI work for the message items
1. Login with WiFi, enter a channel
2. Make sure the last message written in the channel is not yours
(this can be done by joining a new random name channel) 
3. Disconnect from WiFi and wait for disconnected banner to popup
4. Write a message, The Resend label should appear

However, if you have written a message before, the resend button will not appear, since the message gets grouped with the previous message header (containing username and time).

IMO he resend button should not appear only besides the username, but appear in each message individually. i.e.: in this image these 3 messages were sent while i was disconnected, yet the resend button is only available for the first message
![image](https://user-images.githubusercontent.com/1106587/197789011-130744c8-afb3-4536-bc60-dd8f160ce99b.png)

cc: @alexandraB99

2022-10-26 05:33 UTC, elina2015 commented
@richard-ramos yes, it works as you've described! So, I will just open a new issue about the Resend button doesn't appear if there is some messages from me before disconnecting.

2022-10-26 05:34 UTC, elina2015 approved these changes
Tested and approved

2022-11-10 15:49 UTC, merged

2026-08-21 21:22 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (13)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 8415c54e | [567](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/567/) | 2026-08-21 21:22:14 | ~12 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-205329-8415c5-pr7749-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260821-205329-8415c5-pr7749-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | 8415c54e | [2090](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/2090/) | 2026-08-21 21:31:24 | ~18 min | `linux/x86_64` | [:package:`tgz`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-205329-8415c5-pr7749-x86_64.tar.gz) |
| | | | | | | |
| :heavy_check_mark: | c78e3ac1 | [465](https://ci.status.im/job/status-app/job/systems/job/ios/job/aarch64/job/package/465/) | 2026-08-21 21:42:38 | ~18 min | `ios/aarch64` | [:iphone:`ipa`](https://i.diawi.com/RaCk5h) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fi.diawi.com%2FRaCk5h&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | c78e3ac1 | [2195](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2195/) | 2026-08-21 21:47:27 | ~22 min | `macos/aarch64` | [:apple:`dmg`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-205329-c78e3a-pr7749-aarch64.dmg) |
| :heavy_multiplication_x: | c78e3ac1 | [576](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/576/) | 2026-08-21 21:47:36 | ~15 min | `tests/e2e` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/576/allure/) |
| :heavy_check_mark: | c78e3ac1 | [1954](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/package/1954/) | 2026-08-21 22:12:11 | ~42 min | `windows/x86_64` | [:cd:`exe`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260821-205329-c78e3a-pr7749-x86_64.exe) |
| :heavy_check_mark: | c78e3ac1 | [660](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/660/) | 2026-08-21 22:32:09 | ~19 min | `tests/e2e-windows` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/660/allure/) |
| | | | | | | |
| :heavy_check_mark: | af61a2ca | [530](https://ci.status.im/job/status-app/job/systems/job/ios/job/aarch64/job/package/530/) | 2026-08-25 19:37:30 | ~20 min | `ios/aarch64` | [:iphone:`ipa`](https://i.diawi.com/DHp7uS) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fi.diawi.com%2FDHp7uS&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | af61a2ca | [632](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/632/) | 2026-08-25 19:39:20 | ~12 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-191026-af61a2-pr7749-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260825-191026-af61a2-pr7749-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | af61a2ca | [635](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/635/) | 2026-08-25 20:31:23 | ~14 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-200024-af61a2-pr7749-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260825-200024-af61a2-pr7749-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | af61a2ca | [533](https://ci.status.im/job/status-app/job/systems/job/ios/job/aarch64/job/package/533/) | 2026-08-25 21:09:56 | ~27 min | `ios/aarch64` | [:iphone:`ipa`](https://i.diawi.com/vvTfVF) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fi.diawi.com%2FvvTfVF&size=400x400&errorCorrectionLevel=L)|
| :heavy_multiplication_x: | af61a2ca | [640](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/640/) | 2026-08-25 21:14:37 | ~18 min | `tests/e2e` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/640/allure/) |
| :heavy_multiplication_x: | af61a2ca | [715](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/715/) | 2026-08-25 23:18:48 | ~20 min | `tests/e2e-windows` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/tests-e2e/715/allure/) |
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 201833fc | [2165](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/2165/) | 2026-08-25 19:52:25 | ~17 min | `linux/x86_64` | [:package:`tgz`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-191026-201833-pr7749-x86_64.tar.gz) |
| | | | | | | |
| :heavy_check_mark: | 11b83043 | [2168](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/2168/) | 2026-08-25 20:55:52 | ~20 min | `linux/x86_64` | [:package:`tgz`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-200024-11b830-pr7749-x86_64.tar.gz) |
| :heavy_check_mark: | 11b83043 | [2267](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2267/) | 2026-08-25 21:23:20 | ~23 min | `macos/aarch64` | [:apple:`dmg`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-200024-11b830-pr7749-aarch64.dmg) |
| :heavy_check_mark: | 11b83043 | [2024](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/package/2024/) | 2026-08-25 22:57:04 | ~43 min | `windows/x86_64` | [:cd:`exe`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260825-200024-11b830-pr7749-x86_64.exe) |