fix(SplashScreen): Fixed blurry animation
status-im/status-app pull request #7811
Opened 2022-10-07 10:45 UTC by igor-sirotin

Fixes https://github.com/status-im/status-desktop/issues/7810

### Affected areas

splash screen

### Screenshot of functionality (including design for comparison)

#### Before 

<img width="1296" alt="Снимок экрана 2022-10-07 в 13 39 04" src="https://user-images.githubusercontent.com/25482501/194535794-6c69258d-35d5-4b47-b618-eaab6615b2d5.png">

#### After

<img width="1296" alt="Снимок экрана 2022-10-07 в 13 39 34" src="https://user-images.githubusercontent.com/25482501/194535752-aabfe7d8-95ac-4cce-864a-33161a82e16d.png">

2022-10-07 10:50 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 5909eed2 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7811/1/) | 2022-10-07 10:50:22 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7811/1//consoleText) |

2022-10-07 13:02 UTC, MishkaRogachev approved these changes

2022-10-07 13:07 UTC, caybro approved these changes

2022-10-10 06:59 UTC, saledjenic requested changes
@igor-sirotin I think I fixed this issue some time ago (~two months)... blurry animation was because of 2 reasons:
1. width and height for the image were set to some not rounded number
2. the size of gif was 640x640px, but we're displaying it in 128x128 size

Now I see that you changed it to 640x640px again, any reason? Also looking into the animation I don't see what's blurry (or maybe it's up to my resolution/eyes)?

2022-10-10 10:14 UTC, saledjenic approved these changes

2022-10-11 16:29 UTC, merged

2022-10-14 08:26 UTC, saledjenic commented
@igor-sirotin I've checked now both images and see the difference on my side:
![Animaion](https://user-images.githubusercontent.com/86303051/195799021-871c723e-f601-4d97-99e9-6ee48b8d9646.png)

the 640px vairant looks a bit pixelized on my screen around the edge.

2026-09-09 09:59 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | daa6ea0f | [2390](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/2390/) | 2026-09-09 09:59:43 | ~9 min | `linux/x86_64` | [:page_facing_up:`log`](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/2390/consoleText) |
| :heavy_check_mark: | daa6ea0f | [833](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/833/) | 2026-09-09 10:01:42 | ~11 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-260909-095005-daa6ea-pr7811-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-260909-095005-daa6ea-pr7811-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :x: | daa6ea0f | [2226](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/package/2226/) | 2026-09-09 10:03:19 | ~12 min | `windows/x86_64` | [:page_facing_up:`log`](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/package/2226/consoleText) |